name: CI + CD

on: 
  workflow_dispatch  # Manual trigger only - won't run automatically

# on:
#   push:
#     branches:
#       - main  # or your desired source branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      # If you want to push the .next and other build folders, you may need to prepare that
      # e.g. copy build output to a separate directory

      - name: Prepare build directory
        run: |
          rm -rf build-output
          mkdir build-output
          rsync -av --exclude build-output/ --exclude .git/ --exclude .gitignore --exclude .github/ . build-output/
          # Add any other files you need

      - name: Set up git
        run: |
          cd build-output
          git init
          git config user.name "yaseen1546"
          git config user.email "muhammad.yaseen@acquia.com"
          git remote add target nodejsmigration@svn-299.gardens.hosting.acquia.com:nodejsmigration.git

      - name: Set up SSH for SVN
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_NEW }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa
          ssh-keyscan -H svn-299.gardens.hosting.acquia.com >> ~/.ssh/known_hosts

      - name: Commit and push
        run: |
          cd build-output
          git checkout -b ext-ci-cd-normal
          git add .
          git commit -m "Build output from GitHub Actions: $(date '+%Y-%m-%d %H:%M:%S')"
          git push --force target ext-ci-cd-normal
      
      - name: Trigger deployment
        run : |
          ./deploy.sh --client-id=${{ secrets.CLIENT_ID }} --client-secret=${{ secrets.CLIENT_SECRET }} --environment-id=39513-aae8a28a-3199-11f0-a41b-b7397acb7f3d --branch=ext-ci-cd-normal
